# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
  # Log
  monolog.handler.logentries:
      class: Monolog\Handler\LogEntriesHandler
      arguments:
          token: %logentries_token%
